import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Importe o seu LayoutCliente (ajuste o caminho da pasta se necessário)
import LayoutCliente from "./conponents/LayoutCliente"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-br"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex-col">
        {/* O LayoutCliente entra aqui abraçando o children. 
          Ele vai injetar o Cabecario e o MenuLateral com a lógica de clique funcionando!
        */}
        <LayoutCliente>
          {children}
        </LayoutCliente>
      </body>
    </html>
  );
}